baseurl = "https://matiasandina.netlify.com"
DefaultContentLanguage = "en"
title = "Matias Andina"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#useHLJS = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = " "
  logo = "img/m-gray.jpg"
  favicon = "img/webpage_logo.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"


[staticman]
    api= "https://api.staticman.net/v2/entry/matiasandina/Webpage/master/comments"
    pulls= "https://github.com/matiasandina/Webpage/pulls"



[permalinks]
  post = "/:year/:month/:title/"


[Author]
  name = "Matias Andina"
  website = "matiasandina.netlify.com"
  email = "matiasandina@gmail.com"
  github = "matiasandina"
  twitter = "NeuroMLA"
  linkedin = "matias-andina-58a0a4b5"
  
[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1


[[menu.main]]
    identifier = "Research"
    name = "Research"
    weight = 2

# We put the items below the parent "Research"

[[menu.main]]
    parent = "Research"
    name = "Learning and Memory"
    url = "page/Learning-and-Memory"
    weight = 1

[[menu.main]]
    parent = "Research"
    name = "Maternal Behavior"
    url = "page/Maternal-Behavior"
    weight = 2
    

[[menu.main]]
    name = "Teaching"
    url = "page/teaching/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "post/"
    weight = 4


[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 5

