# This is the config.toml for beautifulhugo
# It had some modifications so it might not work right out of the bat...

#baseurl = "https://matiasandina.netlify.com"
#DefaultContentLanguage = "en"
#title = "Matias Andina"
#theme = "hello-friend-ng"
#metaDataFormat = "yaml"
#pygmentsUseClasses = true
#pygmentCodeFences = true
##useHLJS = true
##disqusShortname = "XXX"
##googleAnalytics = "XXX"
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
#
#[Params]
#  subtitle = " "
#  logo = "img/m-gray.jpg"
#  favicon = "img/webpage_logo.ico"
#  dateFormat = "January 2, 2006"
#  commit = false
#  rss = true
#  comments = true
##  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look #and Feel" and change Layout to "Full Width" and Theme to "Classic"#
#
##[[Params.bigimg]]
##  src = "img/triangle.jpg"
##  desc = "Triangle"
##[[Params.bigimg]]
##  src = "img/sphere.jpg"
##  desc = "Sphere"
##[[Params.bigimg]]
##  src = "img/hexagon.jpg"
##  desc = "Hexagon"
#
#[permalinks]
#  post = "/:year/:month/:title/"
#
## Directory name of your blog content (default is `content/posts`)
#contentTypeName = "posts"
## Default theme "light" or "dark"
#defaultTheme = "dark"
#
#
#[Author]
#  name = "Matias Andina"
#  website = "matiasandina.netlify.com"
#  email = "matiasandina@gmail.com"
#  github = "matiasandina"
#  twitter = "NeuroMLA"
#  linkedin = "matias-andina-58a0a4b5"
#
#
#[languages]
#  [languages.en]
#    title = "Matias Andina"
#    subtitle = ""
#    keywords = ""
#    copyright = ""
#    readOtherPosts = "Read other posts"
#
#    [languages.en.params.logo]
#    #  logoText = ""
#    #  logoHomeLink = "/"
#    # or
#    #
#      path = "/img/m-gray.jpg"
#      alt = ""
#
#	# You can create a language based menu
#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "page/about"
#    [[languages.en.menu.main]]
#       identifier = "research"
#       name = "Research"
#       url = "/research"
#    [[languages.en.menu.main]]
#    parent = "Research"
#    name = "Learning and Memory"
#    url = "page/Learning-and-Memory"
#    weight = 1
#
#
## And you can even create generic menu
#[menu]
#  [[menu.main]]
#    identifier = "about"
#    name       = "About"
#    url        = "page/about"
#  [[menu.main]]
#    identifier = "blog"
#    name       = "Blog"
#    url        = "/posts"
#
#  
##[[menu.main]]
##    name = "About"
##    url = "page/about/"
##    weight = 1
#
#
##[[menu.main]]
##    identifier = "Research"
##    name = "Research"
##    weight = 2
#
## We put the items below the parent "Research"
#
##[[menu.main]]
##    parent = "Research"
##    name = "Learning and Memory"
##    url = "page/Learning-and-Memory"
##    weight = 1
#
##[[menu.main]]
##    parent = "Research"
##    name = "Maternal Behavior"
##    url = "page/Maternal-Behavior"
##    weight = 2
#    
#
##[[menu.main]]
##    name = "Teaching"
##    url = "page/teaching/"
##    weight = 3
#
##[[menu.main]]
##    name = "Blog"
##    url = "post/"
##    weight = 4
#
#
##[[menu.main]]
##    name = "Tags"
##    url = "tags"
##    weight = 5

